name: pull_request

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/head/main/' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  verify:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🧰 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: 📦 Install Dependencies
        run: yarn install

      - name: ✨ Linting
        run: yarn lib:lint

      - name: 🧪 Tests
        run: yarn lib:test

      - name: 🏗️ Build
        run: yarn lib:build
